spring:
  application:
    name: referra

  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

    jpa:
      hibernate:
        ddl-auto: validate
      open-in-view: false

    flyway:
      enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.${COGNITO_REGION}.amazonaws.com/${COGNITO_USER_POOL_ID}

management:
  endpoints:
    web:
      exposure:
        include: health,info
